### ISSUE TITLE
announce USDX releases or redirect?

### ISSUE THREAD

**Issue by barbeque-squared** [UltraStar-Deluxe/ultrastar-deluxe.github.io#12]
I kind of forgot that this also existed, so I'd like to know (or discuss): what is _going forward_ the preferred way to announce releases? I see two scenario's:

### Scenario A: individual newsposts
This scenario involves making a new post for every release. It would essentially be a copy of the Github release page, and making individual links sounds like a lot of effort, so most likely I would just link to the Github release page to get the downloads from there?
Things to be discussed/narrowed down:
- Do we keep the Downloads page?
- If yes, how many releases back does it go?
- If no, can the Downloads page be removed and be made instead into a link to the Github Releases page?

### Scenario B: do as much as possible through Github
Basically, remove the Downloads page altogether, and just turn it into a link to the Github Releases page. Alternatively, severely simplify the Downloads page, have a big link to the /latest release near the top, and maybe also a link to the general releases page.

There should probably be a small newspost about how that is now basically the main source of whether or not there is a new version.

Important context: I'm aiming for about 9 or 10 releases per year. Less if there's nothing to release, but still significantly more often than "once every 2-3 years".

But considering this website caters more to end users and less to developers, I don't really know which of these would be the preferred way going forward? As a developer, I'm leaning towards option B, but if A is better for end users, I'd be fine with that, just be ready for small but fairly regular newsposts.

**Comment by basisbit** [comment]
> But considering this website caters more to end users and less to developers, I don't really know which of these would be the preferred way going forward?

I'd suggest asking a couple of users (some that are not software developers) what they prefer.

**Comment by barbeque-squared** [comment]
That's a good idea! I'll ask around a bit and keep some statistics, I'll reply back here once I've gathered sufficient data.

**Comment by barbeque-squared** [comment]
Talked to a few people (both IRL and through the internet) and the consensus I got that the few people that were actually aware of new releases, most were only because they happened to click through to github from the usdx.eu website at some point. A lot of others don't really check either.

I'm not sure from which page they're coming exactly, but there is at least a part of the userbase that relies on usdx.eu for updates.

I think the following would be a good starting point?
1. Make the "Downloads" page a lot simpler (see below)
2. Retro-actively add newsposts + update download page for already-released versions (2023.3 and 2023.4 -- maybe also 2023.5 depending on when 1 gets merged)
3. When doing a new release: PR for newspost + update download page

**Simplifying the Downloads page**
I propose to divide this up into three sections:
- the current release (big version number, some info about bugreporting, otherwise it just links to the relevant github release page).
- "Previous versions" if they're not already there, move artifacts over to github. Each release would be just a link to the relevant github release page.
- "Very old versions" there are some really old versions on there, that don't have a corresponding github release. I'll make them a bit more compact but generally leave them alone.

I'll do it in three consecutive PR's and wait until they're merged each time. The newsposts will just be a link to the github page and a copy of the github release notes. Expect the PR for the simplifying today (or tomorrow at the latest)
