### ISSUE TITLE
Resolution support

### ISSUE THREAD

**Issue by jarredwalton** [UltraStar-Deluxe/ultrastar-deluxe.github.io#4]
Would be good to see native 16:9 and 21:9 support listed on the installation/setup, or just arbitrary resolution support. Right now it only shows 16:10 aspect ratios. Or just remove that from the initial run -- I don't recall where I saw it now, but when the actual game launches, if you select fullscreen on, then the various resolutions all show up properly.

**Comment by basisbit** [comment]
closed because issue in wrong repository.
