### ISSUE TITLE
dbus error when building for Ubuntu 18.04

### ISSUE THREAD

**Issue by MontyGvMC** [UltraStar-Deluxe/ultrastar-deluxe.github.io#5]
Yesterday I tried to build Ultrastar deluxe for Ubuntu 18.04.
The build it self went through without problems but when I tried to start the game I received the following error:

`dbus[27028]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../../dbus/dbus-message.c line 1362.
This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace.
Aborted (core dumped)`

Any hint what could have gone wrong? 
Sorry that I can't provide more details so far, it was the first time I tried to build some project for/on linux.

A side question: Any intentions to bring Ultrastar Deluxxe to the Ubuntu 18.04 software center?

**Comment by basisbit** [comment]
closed because issue in wrong repository
